Repository Keyneez/Keyneez-AOS-Lab, pull requests merged in 2023-01, with the labels that each got.

#13 [UI/#12] card, verification / 카드 및 인증 뷰 구현
  app/build.gradle
  app/src/main/java/com/lab/keyneez/presentation/main/card/CardFragment.kt
  app/src/main/java/com/lab/keyneez/presentation/verification/VerificationActivity.kt
  app/src/main/java/com/lab/keyneez/util/OnSingleClickListener.kt
  app/src/main/java/com/lab/keyneez/util/extension/ViewExt.kt
  app/src/main/res/drawable/ic_card_keyneez.xml
  app/src/main/res/drawable/ic_verification_back.xml
  app/src/main/res/drawable/img_card_cards.xml
  app/src/main/res/drawable/img_verification_card.xml
  app/src/main/res/drawable/shape_black_fill_4_rect.xml
  app/src/main/res/drawable/shape_white_fill_9_rect.xml
  app/src/main/res/layout/activity_verification.xml
  app/src/main/res/layout/fragment_card.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: UI 💄, 채연 🐸, Pull Request 🤗

#14 [FEAT/#11] like / 저장 탭 구현
  app/src/main/java/com/lab/keyneez/data/entity/LikeData.kt
  app/src/main/java/com/lab/keyneez/presentation/main/like/LikeAdapter.kt
  app/src/main/java/com/lab/keyneez/presentation/main/like/LikeFragment.kt
  app/src/main/res/layout/fragment_like.xml
Labels: FEAT ✨, 지은 🐭, Pull Request 🤗

#15 [UI/#3] 홈(infomain) / 뷰페이저 뷰 구현
  app/src/main/java/com/lab/keyneez/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/lab/keyneez/presentation/main/home/NewInfoFragment.kt
  app/src/main/java/com/lab/keyneez/presentation/main/home/PopularInfoFragment.kt
  app/src/main/java/com/lab/keyneez/presentation/main/home/RecommendInfoFragment.kt
  app/src/main/java/com/lab/keyneez/presentation/main/home/adapter/HomeVPFragmentAdapter.kt
  app/src/main/res/drawable/haedal.jpg
  app/src/main/res/drawable/ic_home_search.xml
  app/src/main/res/drawable/img_home_logo.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_new.xml
  app/src/main/res/layout/fragment_home_popular.xml
  app/src/main/res/layout/fragment_home_recommend.xml
  app/src/main/res/layout/item_infomain.xml
  app/src/main/res/values/strings.xml
Labels: UI 💄, 동주 🦦, Pull Request 🤗
